/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Zigbee */

#ifndef _Included_Zigbee
#define _Included_Zigbee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Zigbee
 * Method:    onLEDNative
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_teamsf_zigbeetest_Zigbee_onLEDNative
  (JNIEnv *, jclass, jchar);

/*
 * Class:     Zigbee
 * Method:    offLEDNative
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_teamsf_zigbeetest_Zigbee_offLEDNative
  (JNIEnv *, jclass, jchar);

/*
 * Class:     Zigbee
 * Method:    upDimNative
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_teamsf_zigbeetest_Zigbee_upDimNative
  (JNIEnv *, jclass, jchar);

/*
 * Class:     Zigbee
 * Method:    downDimNative
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_teamsf_zigbeetest_Zigbee_downDimNative
  (JNIEnv *, jclass, jchar);

#ifdef __cplusplus
}
#endif
#endif
